-- H2-compatible mirror of V11__create_discovery_sweep.sql for Flyway integration tests.
-- BIGSERIAL → BIGINT GENERATED BY DEFAULT AS IDENTITY (matches V4 audit_log mirror pattern).
-- TIMESTAMPTZ → TIMESTAMP WITH TIME ZONE.
CREATE TABLE discovery_sweep (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  started_at TIMESTAMP WITH TIME ZONE NOT NULL,
  finished_at TIMESTAMP WITH TIME ZONE,
  source TEXT NOT NULL,
  iface TEXT,
  neighbor_count INT NOT NULL DEFAULT 0,
  device_count INT NOT NULL DEFAULT 0,
  triggered_by TEXT NOT NULL,
  audit_log_id BIGINT REFERENCES audit_log(id),
  status TEXT NOT NULL
);
CREATE INDEX idx_discovery_sweep_started ON discovery_sweep(started_at DESC);
