-- V14 H2 mirror: scheduled scan policies + scan.retry_count column.
-- H2 MODE=PostgreSQL accepts BIGSERIAL as IDENTITY synonym.
-- TIMESTAMP WITH TIME ZONE → H2 uses TIMESTAMP WITH TIME ZONE; we strip the
-- timezone-aware default and use CURRENT_TIMESTAMP for portability.

CREATE TABLE scan_policy (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    cron_expression VARCHAR(255) NOT NULL,
    cidr VARCHAR(64) NOT NULL,
    scan_type VARCHAR(64) NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_triggered_at TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_scan_policy_enabled
    ON scan_policy (enabled);

ALTER TABLE scan ADD COLUMN retry_count INTEGER NOT NULL DEFAULT 0;
