-- V15 H2 mirror: integration_config (encrypted credentials, JSON config).
-- H2 BYTEA equivalent is VARBINARY; use a generous cap so the column never
-- truncates a small AES-GCM payload (12-byte IV + ciphertext + 16-byte tag).

CREATE TABLE integration_config (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    integration_type VARCHAR(64) NOT NULL UNIQUE,
    config_json VARCHAR(4096) NOT NULL,
    encrypted_credentials VARBINARY(4096) NOT NULL,
    last_push_at TIMESTAMP,
    last_push_status VARCHAR(256),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
