-- H2-compatible version of V1__create_device.sql for Flyway integration tests.
-- Differences from production script:
--   BIGSERIAL -> BIGINT GENERATED BY DEFAULT AS IDENTITY
--   TIMESTAMPTZ -> TIMESTAMP WITH TIME ZONE
CREATE TABLE device (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ip_address TEXT NOT NULL,
  hostname TEXT,
  mac_address TEXT,
  first_seen TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  last_seen TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  CONSTRAINT device_ip_unique UNIQUE (ip_address)
);
