-- H2-compatible mirror of V29.
CREATE TABLE remote_agent_token (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  label VARCHAR(128) NOT NULL,
  token_hash VARCHAR(255) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  created_by VARCHAR(64),
  revoked BOOLEAN NOT NULL DEFAULT FALSE,
  revoked_at TIMESTAMP WITH TIME ZONE,
  last_used_at TIMESTAMP WITH TIME ZONE
);
CREATE INDEX idx_remote_agent_token_revoked ON remote_agent_token(revoked);
