-- H2-compatible version of V3__create_scan.sql for Flyway integration tests.
CREATE TABLE scan (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cidr TEXT NOT NULL,
  scan_type TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'PENDING',
  requested_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  completed_at TIMESTAMP WITH TIME ZONE
);
