-- H2-compatible mirror of V5__create_cve.sql
-- Differences from production script:
--   BIGSERIAL -> BIGINT GENERATED BY DEFAULT AS IDENTITY
--   TIMESTAMPTZ -> TIMESTAMP WITH TIME ZONE
--   now() -> CURRENT_TIMESTAMP
CREATE TABLE cve (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cve_id TEXT NOT NULL UNIQUE,
  published TIMESTAMP WITH TIME ZONE,
  last_modified TIMESTAMP WITH TIME ZONE NOT NULL,
  vuln_status TEXT,
  description TEXT,
  cvss_v31_score NUMERIC(3,1),
  cvss_v31_vector TEXT,
  cvss_v30_score NUMERIC(3,1),
  cvss_v30_vector TEXT,
  cvss_v2_score NUMERIC(3,1),
  cvss_v2_vector TEXT,
  raw_json TEXT NOT NULL,
  fetched_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX cve_last_modified_idx ON cve (last_modified);

CREATE TABLE cve_cpe_match (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cve_fk BIGINT NOT NULL REFERENCES cve(id) ON DELETE CASCADE,
  cpe23_uri TEXT NOT NULL,
  vulnerable BOOLEAN NOT NULL,
  version_start_including TEXT,
  version_start_excluding TEXT,
  version_end_including TEXT,
  version_end_excluding TEXT
);
CREATE INDEX cve_cpe_match_cpe23_uri_idx ON cve_cpe_match (cpe23_uri);
CREATE INDEX cve_cpe_match_cve_fk_idx ON cve_cpe_match (cve_fk);
