-- H2-compatible mirror of V6__create_risk_tables.sql
-- Differences from production script:
--   BIGSERIAL -> BIGINT GENERATED BY DEFAULT AS IDENTITY
--   TIMESTAMPTZ -> TIMESTAMP WITH TIME ZONE
--   now() -> CURRENT_TIMESTAMP
CREATE TABLE epss_score (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cve_id TEXT NOT NULL UNIQUE,
  epss NUMERIC(7,6) NOT NULL,
  percentile NUMERIC(7,6) NOT NULL,
  score_date DATE NOT NULL,
  ingested_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX epss_score_score_date_idx ON epss_score (score_date);

CREATE TABLE kev_entry (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cve_id TEXT NOT NULL UNIQUE,
  vendor_project TEXT,
  product TEXT,
  vulnerability_name TEXT,
  date_added DATE NOT NULL,
  short_description TEXT,
  required_action TEXT,
  due_date DATE,
  known_ransomware_campaign_use TEXT,
  notes TEXT,
  cwes TEXT,
  ingested_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX kev_entry_date_added_idx ON kev_entry (date_added);

ALTER TABLE device ADD COLUMN criticality TEXT NOT NULL DEFAULT 'MEDIUM'
  CHECK (criticality IN ('LOW','MEDIUM','HIGH','CRITICAL'));
